version: '3.8'

services:
  db:
    build: .
    ports:
      - "1450:5432"  # Пробросим локальный порт 1450 на порт 5432 контейнера
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data  # Для хранения данных

volumes:
  pgdata:
